# buildspec is used by aws codepipeline
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

cache:
  paths:
    - 'node_modules/**/*' # Cache 'node_modules' for faster yarn

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging into Amazon ECR
      - $(aws ecr get-login --no-include-email --region us-west-1)
      - REPOSITORY_URL=213288384225.dkr.ecr.us-west-1.amazonaws.com/frontend
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=FRONTEND-${COMMIT_HASH}
  build:
    commands:
      - echo Build started on `date`
      - echo IMAGE_TAG is $IMAGE_TAG
      - echo Build the Docker image...
      - docker build -t $REPOSITORY_URL:$IMAGE_TAG . # TODO: add build-args
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URL:$IMAGE_TAG
      - echo Writing image definition file
      - printf '[{"name":"frontend","imageUri":"%s"}]' $REPOSITORY_URL:$IMAGE_TAG > imagedef.json
artifacts:
  files:
    - imagedef.json
