name: Newsfeed Countinuos Integration

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
      - run: yarn install --frozen-lockfile
      - run: yarn build:web
      - run: yarn build:mobile

  test_cocoapod_install:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install Yarn Dependencies
        run: yarn

      - name: setup-cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          podfile-path: packages/mobile/ios/Podfile.lock

      - name: Pod install Dependencies
        run: |
          cd packages/mobile/ios
          pod install

      - name: Run IOS. OPEN WITH CARE!! This might freeze your browzer
        run: |
          cd packages/mobile
          yarn ios
