name: Newsfeed Countinuos Integration

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
      - run: yarn
      - run: yarn build:web

  test_cocoapod_install:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ty0x2333/cocoapods-action@master
      - run: |
          cd packages/mobile/ios
          pod install
